routes/web.php
<?php

use App\Models\AffiliatedAccountService;
use App\Models\Companies;
use Carbon\Carbon;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', 'WelcomeController@index')->name('/');
Route::get('/login', 'WelcomeController@index')->name('login');


Route::get('/inicio', 'WelcomeController@index')->name('home');
Route::get('/home', 'WelcomeController@index')->name('home');

Route::get('/acercade', function () {
    return view('aboutus');
})->name('aboutus');

Route::get('/enfoque_pedagogico', function () {
    return view('pedagogy');
})->name('pedagogy');

Route::get('/contactenos', function () {
    return view('contactus');
})->name('contactus');

Route::get('/guias_de_aprendizaje', function () {
    return view('sequences.search');
})->name('sequences.search');

Route::get('/guia_de_aprendizaje/{sequence_id}/{sequence_name}', 'CompanyController@show_company_sequences')->name('show_company_sequences');

Route::get('/implementos_de_laboratorio', function () {
    return view('elementsKits.search');
})->name('elementsKits.search');


Route::get('/dialog_template_detail_user', function () {
    return view('roles.admin.dialog_template_detail_user');
})->name('dialog_template_detail_user');


Route::get('/kit_de_laboratorio/{kit_id}/{kit_name}', 'KitController@showKitDetail')->name('elementsKits.getKit');
Route::get('/elemento_de_laboratorio/{element_id}/{element_name}', 'ElementController@showElementDetail')->name('elementsKits.getElement');

Route::get('/planes_de_acceso', function () {
    return view('ratingPlan.list');
})->name('ratingPlan.list');

Route::get('/plan_de_acceso/{rating_plan_id}/{rating_name}/{sequence_id?}', 'RatingPlanController@showRatingPlan')->name('ratingPlan.detailSequence');

Route::get('page500', function(){
    return view('page500',['companies'=>Companies::all()]);
})->name('page500');

Route::get('/terminos_condiciones', function () {
    return view('terms-conditions-social');
})->name('terms_conditions_social');

Route::get('/tutoriales', 'HelpPlatformController@index')->name('help_platform');

//routes login
Route::get('validate_registry_free_plan/{ratingPlanId}', 'Auth\RegisterController@validate_registry_free_plan')->name('validate_registry_free_plan');
Route::get('registro_afiliado/{error_email_social?}/{email?}', 'Auth\RegisterController@show_register')->name('registerForm');
Route::get('{empresa}/loginform', 'DataAffiliatedCompanyController@index')->middleware('company')->name('loginform');
Route::get('conexiones/loginform/admin', ['as' => 'loginformadmin', 'uses' => 'DataAffiliatedCompanyController@index_admin']);
Route::prefix('user')
    ->as('user.')
    ->group(function() {
        Route::namespace('Auth\Login')
            ->group(function() {
                Route::get('login/{empresa?}', 'AffiliatedCompanyController@showLoginForm')->name('showLogin');
                Route::post('login/{rol?}', 'AffiliatedCompanyController@login')->name('login');
                Route::post('logout', 'AffiliatedCompanyController@logout')->name('logout');
            });
        Route::get('home', 'Home\AfiliadoHomeController@index')->name('home');
        Route::get('redirectfacebook/{rol}/{action}', 'Auth\LoginController@redirectToProvider')->name('redirectfacebook');
        Route::get('callback', 'Auth\LoginController@handleProviderCallback')->name('callback');
        Route::get('redirectgmail/{rol}/{action}', 'Auth\LoginController@redirectToProviderGmail')->name('redirectgmail');
        Route::get('callbackgmail', 'Auth\LoginController@handleProviderCallbackGmail')->name('callbackgmail');
    });
Route::get('login/github/callback', 'Auth\LoginController@handleProviderCallback');
Route::get('callbackgmail', 'Auth\LoginController@handleProviderCallbackGmail')->name('callbackgmail');

//routes admin
Route::group(['middleware' =>['auth:afiliadoempresa']],function (){
    Route::get('conexiones/admin/get_users_contracted_products_view', 'AdminController@get_users_contracted_products_view')->middleware('role:admin')->name('get_users_contracted_products_view');
    Route::get('conexiones/admin/get_user_contracted_products_view/{affiliatedId?}', 'AdminController@get_user_contracted_products_view')->middleware('role:admin')->name('get_user_contracted_products_view');
    Route::get('conexiones/admin/get_users_contracted_products_dt/', 'AdminController@get_users_contracted_products_dt')->middleware('role:admin')->name('get_users_contracted_products_dt');
    Route::get('conexiones/admin/get_user_contracted_products_dt/{affiliatedId?}', 'AdminController@get_user_contracted_products_dt')->middleware('role:admin')->name('get_user_contracted_products_dt');
    Route::post('conexiones/admin/update_date_expiration_content_user', 'AdminController@update_date_expiration_content_user')->middleware('role:admin')->name('update_date_expiration_content_user');
    Route::get('conexiones/admin/plans_view', 'AdminController@plans_view')->middleware('role:admin')->name('plans_view');
    Route::get('conexiones/admin/get_plans_dt', 'RatingPlanController@get_plans_dt')->middleware('role:admin')->name('get_plans_dt');
    Route::get('conexiones/admin/management_kit_elements_view', 'AdminController@management_kit_elements_view')->middleware('role:admin')->name('management_kit_elements_view');
    Route::post('conexiones/admin/create_or_update_kit/{action?}', 'KitController@create_or_update_kit')->middleware('role:admin')->name('create_or_update_kit');
    Route::post('conexiones/admin/create_or_update_element/{action?}', 'ElementController@create_or_update_element')->middleware('role:admin')->name('create_or_update_element');
    Route::get('conexiones/admin/get_kit_element_dt', 'KitElementController@get_kit_element_dt')->middleware('role:admin')->name('get_kit_element_dt');
    Route::get('conexiones/admin/get_elements', 'ElementController@get_elements')->middleware('role:admin')->name('get_elements');
    Route::get('conexiones/admin/get_element/{id?}', 'ElementController@get_element')->middleware('role:admin')->name('get_element');
    Route::post('conexiones/admin/delete_elementorkit_in_moment', 'KitElementController@delete_elementorkit_in_moment')->middleware('role:admin')->name('delete_elementorkit_in_moment');
    Route::get('conexiones/admin/get_kit/{id?}', 'KitController@get_kit')->middleware('role:admin')->name('get_kit');
    Route::get('conexiones/admin/usuarios/', 'AdminController@show_all_users')->middleware('role:admin')->name('admin.all_users');
    Route::get('conexiones/admin/get_all_users/', 'AdminController@get_all_users')->middleware('role:admin')->name('admin.get_all_users');
    Route::get('conexiones/admin/get_user/{user_id}', 'AdminController@get_user')->middleware('role:admin')->name('admin.get_user');
    Route::get('conexiones/admin/get_user_shoppingCart/{idShoppingCart}', 'AdminController@get_user_shoppingCart')->middleware('role:admin')->name('admin.get_user_shoppingCart');
    Route::get('conexiones/admin/paginas', 'AdminController@management_pages')->middleware('role:admin')->name('management_pages');
    Route::get('conexiones/admin/get_pages', 'AdminController@get_pages')->middleware('role:admin')->name('admin.get_pages');
    Route::post('conexiones/admin/update_page', 'AdminController@update_page')->middleware('role:admin')->name('update_page');
    Route::get('conexiones/admin/transacciones', 'AdminController@show_all_transaction')->middleware('role:admin')->name('admin.show_all_transaction');
    Route::get('conexiones/admin/preguntas_frecuentes', 'AdminController@frequent_question_page')->middleware('role:admin')->name('frequent_question_page');
    Route::post('conexiones/admin/update_or_crate_question', 'AdminController@update_or_crate_question')->middleware('role:admin')->name('admin.update_or_crate_question');
    Route::post('conexiones/admin/delete_question', 'AdminController@delete_question')->middleware('role:admin')->name('admin.delete_question');
});


Route::post('edit_image_perfil', 'TutorController@edit_image_perfil')->middleware('role:tutor')->name('edit_image_perfil');

Route::group(['middleware' =>['auth:afiliadoempresa', 'companyaffiliated', 'company'] ], function() {

    Route::get('{empresa}/teacher', 'TeacherController@index')->middleware('role:teacher')->name('teacher');
    Route::get('{empresa}/tutor', 'TutorController@index')->middleware('role:tutor')->name('tutor');
    Route::get('{empresa}/tutor/inscripciones', 'TutorController@showInscriptions')->middleware('role:tutor')->name('tutor.inscriptions');
    Route::get('{empresa}/tutor/productos', 'TutorController@showProducts')->middleware('role:tutor')->name('tutor.products');
    Route::get('{empresa}/tutor/historial_de_pagos', 'TutorController@showHistory')->middleware('role:tutor')->name('tutor.history');
    Route::get('{empresa}/tutor/carrito_de_compras', 'TutorController@showWishList')->middleware('role:tutor')->name('tutor.wishList');
    Route::get('{empresa}/student/', 'StudentController@index')->middleware('role:student')->name('student');
    Route::get('{empresa}/admin/', 'AdminController@index')->middleware('role:admin')->name('admin');
    Route::get('{empresa}/student/avatar', 'AvatarController@index')->middleware('role:student','company')->name('student.avatar');
    Route::post('{empresa}/student/update_avatar', 'AvatarController@update_avatar')->middleware('role:student')->name('update_avatar');
    Route::get('{empresa}/student/secuencias', 'StudentController@show_available_sequences')->middleware('role:student')->name('student.available_sequences');

app/Models/Roles.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Roles extends Model
{
    //

    public function users()
    {
        return $this->belongsToMany('App\Models\AfiliadoEmpresa', 'afiliado_empresa_roles', 'rol_id', 'afiliado_empresa_id')->withTimestamps();
    }

}

resources/views/roles/tutor/edit_student.blade.php
<form novalidate name="myForm">
    <div class="">
        <div class="row">
            <h6><i class="fa fas fa-arrow-right arrow-icon"></i>Registra los datos del estudiantess</h6>
            <div class="col-12 d-flex mt-3">
                <div class="register-avatar-kid" ng-click="onKidSelected('niño')" ng-class="{'selected':newStudent.kidSelected==='niño'}">
                    <img src="{{asset('images/icons/kid2.png')}}" width="93px;" height="auto"/>
                    <h6>Niño</h6>
                </div>
                <div class="register-avatar-kid" ng-click="onKidSelected('niña')" ng-class="{'selected':newStudent.kidSelected==='niña'}">
                    <img src="{{asset('images/icons/kid1.png')}}" width="93px;" height="auto"/>
                    <h6>Niña</h6>
                </div>
                <div class="register-avatar-kid" ng-click="onKidSelected('joven')" ng-class="{'selected':newStudent.kidSelected==='joven'}" style="width: 218px;">
                    <img src="{{asset('images/icons/kid3.png')}}" width="186px;" height="auto"/>
                    <h6>Joven</h6>
                </div>
            </div>

            <div class="form-group col-lg-4">
                <label class=""><i class="fa fas fa-arrow-right arrow-icon"></i>{{ __('Nombre') }}</label>
                <input placeholder="" type="text" name="name" ng-model="newStudent.name" required
                       class="form-control @error('name') is-invalid @enderror" value="">
                @error('name')
                <span class="invalid-feedback" role="alert">
                     <strong>{{ $message }}</strong>
                  </span>
                @enderror
            </div>
            <div class="form-group col-lg-4">
                <label class="">{{ __('Apellido') }}</label>
                <input placeholder="" type="text" name="last_name"  ng-model="newStudent.last_name" required
                       class="form-control @error('last_name') is-invalid @enderror" value="">
                @error('last_name')
                <span class="invalid-feedback" role="alert">
                     <strong>{{ $message }}</strong>
                  </span>
                @enderror
            </div>
            <div class="form-group col-lg-4">
                <label class="">{{ __('Fecha de nacimiento') }}</label>
                <input placeholder="día/mes/año" type="date" name="birthday"  ng-model="newStudent.birthday"
                       class="form-control @error('birthday') is-invalid @enderror" value="">
                @error('birthday')
                <span class="invalid-feedback" role="alert">
                     <strong>{{ $message }}</strong>
                  </span>
                @enderror
            </div>
            <div class="form-group col-lg-4">
                <label class=""><i class="fa fas fa-arrow-right arrow-icon"></i>{{ __('Usuario') }}</label>
                <input placeholder="" type="text" name="user_name" ng-blur="onValidateUserName()" ng-keydown="onValidateUserName()" ng-model="newStudent.user_name" required
                       class="form-control" value="" ng-class="(validateUserName)?'':'is-invalid'">
                <span class="invalid-feedback" role="alert">
                     <strong>Usuario no disponible</strong>
                </span>
            </div>
            <div class="form-group col-lg-6">
                <label class=""><i class="fa fas fa-arrow-right arrow-icon"></i>{{ __('Asignar y/o modificar contraseña') }}</label>
                <div class="input-group">
                    <input ID="txtPassword" type="Password" name="password"  ng-model="newStudent.password"
                           class="form-control @error('last_name') is-invalid @enderror" value="">
                    <div class="input-group-append">
                        <button id="show_password" class="btn btn-primary" type="button" ng-click="viewPassword('txtPassword')"> <span class="fa fa-eye-slash icon txtPassword"></span> </button>
                    </div>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-small btn-primary d-flex" ng-click="onEditStudent()" ng-disabled="(myForm.$invalid || myForm.$pending) || !validateUserName">
            <div ng-show="loadingRegistry"><i class="fa fa-spinner fa-spin mr-2"></i></div>
            {{ __('Editar Registro') }}
        </button>
        <span ng-show="errorMessageRegister" class="invalid-feedback" role="alert">
                 <strong>@{{errorMessageRegister}}</strong>
        </span>
    </div>
</form>

resources/views/roles/tutor/tutor_navbar.blade.php
<nav ng-controller="navbarController" id="navbar" class="pb-0 navbar-glass sticky-top-ie row navbar-top sticky-kit navbar navbar-expand-lg navbar-light">
  <button aria-label="Toggle navigation" id="toggleMenu" type="button" class="navbar-toggler">
  <span class="navbar-toggler-icon"></span>
  </button>
  <a class="text-decoration-none navbar-brand text-left ml-3" id="topLogo" href="#">
     <div class="d-flex align-items-center">
        <a href="{{asset('/')}}"><img href="" class="mr-2 avatar-logo" src="{{ asset('images/icons/iconosoloConexiones-01.png') }}" alt="Logo" width="40"></a>
        <div class="text-sans-serif text-center fs-sm--3 fs-md--2 fs-lg-0 font-weight-semi-bold" style="min-width: 154px;">
           <span id="slogan" >Experiencias científicas <br/> para conocer el mundo <br/> natural</span>
        </div>
     </div>
  </a>
  @auth('afiliadoempresa')
  @if(auth('afiliadoempresa')->user())
     @if(auth('afiliadoempresa')->user()->hasAnyRole('tutor'))
     <ul class="nav collapse navbar-collapse row text-align-rigth row">
		
		
		
     </ul>
     @endif
  @endif
  @endauth
  @guest('afiliadoempresa')
     <ul class="ml-1 nav collapse navbar-collapse row text-align fs--1 font-weight-semi-bold">
        <li class="nav-item col-1 p-0 nav-small-fs--1"><a href="{{ route('home') }}" class="nav-link p-0 pb-1 @if(\Route::current()->getName() == 'home' || Route::current()->getName() == '/') selected @endif">Inicio</a></li>
        <li class="nav-item col-1-5 p-0 "><a href="{{ route('aboutus') }}" class="nav-link p-0 pb-1 @if(\Route::current()->getName() == 'aboutus') selected @endif">Acerca de conexiones</a></li>
        <li class="nav-item col-1-5 p-0"><a href="{{ route('sequences.search') }}" class="nav-link p-0 pb-1 
        @if(\Route::current()->getName() == 'sequences.search') selected @endif
        @if(\Route::current()->getName() == 'sequences.get') selected @endif
        ">Guías de aprendizaje</a></li>
        <li class="nav-item col-2 p-0"><a href="{{ route('elementsKits.search') }}" class="nav-link p-0 pb-1 @if(\Route::current()->getName() == 'elementsKits.search') selected @endif">Implementos de laboratorio</a></li>
        <li class="nav-item ml-2 col-1-6 p-0"><a href="{{ route('contactus') }}" class="nav-link p-0 pb-1 @if(\Route::current()->getName() == 'contactus') selected @endif">Contáctenos</a></li>
        <li class="ml-2 nav-item col-2 p-0 text-align-right">
           <a class="btn btn-primary btn-sm badge-pill fs-lg--1" href="{{ route('user.showLogin') }}">Inicio de Sesión</a>
        </li>
        <li class="ml-2 nav-item p-0">
           <a class="btn btn-secondary btn-sm badge-pill  fs-lg--1" href="{{ route('registerForm') }}">Registro</a>
        </li>
        <li class="nav-item">
           <a class="px-0 notification-indicator notification-indicator-warning notification-indicator-fill nav-link" href="{{route('shoppingCart')}}">
              <span class="notification-indicator-number" ng-init="initNumberShoppingCart()">0</span>
              <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="shopping-cart" class="svg-inline--fa fa-shopping-cart fa-w-18 fs-4" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" style="transform-origin: 0.5625em 0.5em;">
                 <g transform="translate(288 256)">
                    <g transform="translate(0, 0)  scale(0.5625, 0.5625)  rotate(0 0 0)">
                       <path fill="currentColor" d="M528.12 301.319l47.273-208C578.806 78.301 567.391 64 551.99 64H159.208l-9.166-44.81C147.758 8.021 137.93 0 126.529 0H24C10.745 0 0 10.745 0 24v16c0 13.255 10.745 24 24 24h69.883l70.248 343.435C147.325 417.1 136 435.222 136 456c0 30.928 25.072 56 56 56s56-25.072 56-56c0-15.674-6.447-29.835-16.824-40h209.647C430.447 426.165 424 440.326 424 456c0 30.928 25.072 56 56 56s56-25.072 56-56c0-22.172-12.888-41.332-31.579-50.405l5.517-24.276c3.413-15.018-8.002-29.319-23.403-29.319H218.117l-6.545-32h293.145c11.206 0 20.92-7.754 23.403-18.681z" transform="translate(-288 -256)"></path>
                    </g>
                 </g>
              </svg>
           </a>
        </li>
        <li class="nav-item ml-auto mr-auto">
           <form class="search-box form-inline ng-pristine ng-valid">
              <input placeholder="Buscar..." aria-label="Search" type="search" class="rounded-pill search-input form-control">
              <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="search" class="svg-inline--fa fa-search fa-w-16 position-absolute text-400 search-box-icon" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                 <path fill="currentColor" d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z"></path>
              </svg>
           </form>
        </li>
     </ul>
  @endguest
</nav>

resources/views/roles/tutor/tutor_sidebar.blade.php
<nav ng-controller="navbarController"  id="sideMenu" class="navbar-vertical navbar-glass navbar navbar-expand-xl navbar-light max-width-sidemenu"
   style="display:none">
   <div class="collapse show navbar-collapse" aria-expanded="true" style="">
      <div class="ScrollbarsCustom trackYVisible"
         style="position: relative; width: 100%; height: 85vh; display: block;">
         <div class="ScrollbarsCustom-Wrapper"
            style="position: absolute; top: 0px; left: 0px; bottom: 0px; right: 10px; overflow: hidden;">
            <div class="ScrollbarsCustom-Scroller"
               style="position: absolute; top: 0px; left: 0px; bottom: 0px; right: 0px; direction: ltr; overflow: hidden scroll; padding-right: 20px; margin-right: -21px;">
               <div class="ScrollbarsCustom-Content"
                  style="box-sizing: border-box; padding: 0.05px; min-height: 100%; min-width: 100%;">
                  
                  <ul class="navbar-nav flex-column">
                  @auth('afiliadoempresa')
                    @if(auth('afiliadoempresa')->user())
                     @if(auth('afiliadoempresa')->user()->hasAnyRole('student'))
                        <li class="nav-item">
                            <a class="nav-link" aria-expanded="false" href="{{ route('student', auth('afiliadoempresa')->user()->company_name()) }}" >
                               <div class="d-flex align-items-center">
                                  <span class="ml-2 mr-2 nav-link-icon">
                                     <i class="fas fa-user fs-1"></i>
                                  </span>
                                  Mi perfíl
                               </div>
                            </a>
                        </li>
                     
                        <li class="nav-item">
                            <a class="nav-link" aria-expanded="false" href="{{ route('student.available_sequences',auth('afiliadoempresa')->user()->company_name()) }}" >
                               <div class="d-flex align-items-center">
                                  <span class="ml-2 mr-2 nav-link-icon">
                                     <i class="fas fa-book-open fs-1"></i>
                                  </span>
                                  Guías de aprendizaje
                               </div>
                            </a>
                        </li>
                      @endif
                    @endif
                  @endauth
                         
                     <li class="nav-item">
                        <a class="nav-link" href="{{ route('home') }}">
                           <div class="d-flex align-items-center">
                              <span>Inicio</span>
                           </div>
                        </a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{{ route('aboutus') }}">
                           <div class="d-flex align-items-center">
                              <span>Acerca de conexiones</span>
                           </div>
                        </a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{{ route('sequences.search') }}">
                           <div class="d-flex align-items-center">
                              <span>Guías de aprendizaje</span>
                           </div>
                        </a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{{ route('elementsKits.search') }}">
                           <div class="d-flex align-items-center">
                              <span>Implementos de laboratorio</span>
                           </div>
                        </a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{{ route('contactus') }}">
                           <div class="d-flex align-items-center">
                              <span></span>
                              <span>Contáctenos</span>
                           </div>
                        </a>
                     </li>
                  </ul>
                  <ul class="navbar-nav flex-column">
                     <li class="nav-item">
                        <a class="nav-link" aria-expanded="false" href="{{ route('shoppingCart') }}">
                           <div class="d-flex align-items-center">
                              <span class="mr-3 nav-link-icon">
                                 <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="shopping-cart"
                                    class="svg-inline--fa fa-shopping-cart fa-w-18 fs-4" role="img"
                                    xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"
                                    style="transform-origin: 0.5625em 0.5em;">
                                    <g transform="translate(288 256)">
                                       <g transform="translate(0, 0)  scale(0.5625, 0.5625)  rotate(0 0 0)">
                                          <path fill="currentColor"
                                             d="M528.12 301.319l47.273-208C578.806 78.301 567.391 64 551.99 64H159.208l-9.166-44.81C147.758 8.021 137.93 0 126.529 0H24C10.745 0 0 10.745 0 24v16c0 13.255 10.745 24 24 24h69.883l70.248 343.435C147.325 417.1 136 435.222 136 456c0 30.928 25.072 56 56 56s56-25.072 56-56c0-15.674-6.447-29.835-16.824-40h209.647C430.447 426.165 424 440.326 424 456c0 30.928 25.072 56 56 56s56-25.072 56-56c0-22.172-12.888-41.332-31.579-50.405l5.517-24.276c3.413-15.018-8.002-29.319-23.403-29.319H218.117l-6.545-32h293.145c11.206 0 20.92-7.754 23.403-18.681z"
                                             transform="translate(-288 -256)"></path>
                                       </g>
                                    </g>
                                 </svg>
                              </span>
                              Carrito de compras
                           </div>
                        </a>
                     </li>
                     @auth('afiliadoempresa')
                         @if(auth('afiliadoempresa')->user()->hasAnyRole('tutor'))
                         <li class="nav-item">
                            <a class="nav-link"
                               ng-href="{{ route('tutor',auth('afiliadoempresa')->user()->company_name()) }}">
                               <div class="d-flex align-items-center">
                                  <span></span>
                                  <span>Ver estado</span>
                               </div>
                            </a>
                         </li>
                         @elseif(auth('afiliadoempresa')->user()->hasAnyRole('student'))
                         <li class="nav-item">
                            <a class="nav-link"
                               ng-href="{{ route('student',auth('afiliadoempresa')->user()->company_name()) }}">
                               <div class="d-flex align-items-center">
                                  <span></span>
                                  <span>Perfíl &amp; cuenta</span>
                               </div>
                            </a>
                         </li>
                         @endif
                         @if(auth('afiliadoempresa')->user()->hasAnyRole('admin'))
                         <li class="nav-item">
                            <a class="nav-link"
                               ng-href="{{ route('admin',auth('afiliadoempresa')->user()->company_name()) }}">
                               <div class="d-flex align-items-center">
                                  <span></span>
                                  <span>Configuración</span>
                               </div>
                            </a>
                         </li>
                         @endif                         
                         <li class="mt-1 nav-item">
                            <a class="my-3 btn btn-primary btn-sm btn-block" href="{{ route('user.logout') }}"
                              ng-click="closeSession('{{ route('user.logout') }}')">Cerrar
                               Sesión</a>
                         </li>
                     @else
                     <li class="nav-item">
                        <a class="btn btn-primary btn-sm" href="{{ route('user.login') }}">Iniciar Sesión</a>
                     </li>
                     <li class="mt-2 nav-item">
                        <a class="btn btn-secondary btn-sm" href="{{ route('register') }}">Registro gratis</a>
                     </li>
                     @endauth
                  </ul>
               </div>
            </div>
         </div>
         <span class="TrackY" axis="y"
            style="position: absolute; overflow: hidden; border-radius: 4px; background: rgba(0, 0, 0, 0.1); user-select: none; width: 10px; height: calc(100% - 20px); top: 10px; right: 0px;">
            <div class="ScrollbarsCustom-Thumb ScrollbarsCustom-ThumbY"
               style="touch-action: none; cursor: pointer; border-radius: 4px; background: rgba(0, 0, 0, 0.4); width: 100%; height: 348.506px; transform: translateY(0px);">
            </div>
         </span>
         <div class="ScrollbarsCustom-Track ScrollbarsCustom-TrackX"
            style="position: absolute; overflow: hidden; border-radius: 4px; background: rgba(0, 0, 0, 0.1); user-select: none; height: 10px; width: calc(100% - 20px); bottom: 0px; left: 10px; display: none;">
            <div class="ScrollbarsCustom-Thumb ScrollbarsCustom-ThumbX"
               style="touch-action: none; cursor: pointer; border-radius: 4px; background: rgba(0, 0, 0, 0.4); height: 100%; width: 0px; display: none;">
            </div>
         </div>
      </div>
   </div>
</nav>

resources/views/roles/tutor/wish_list.blade.php
@extends('roles.tutor.layout')

@section('content-tutor-index')
   
	@include('shopping/pending_shopping_cart')
   
@endsection
@section('js')
    <script src="{{asset('/../angular/controller/tutorProductsCtrl.js')}}"></script>
@endsection